name: Update Master EPG

on:
  schedule:
    - cron: '0 3 * * *' # Her gece TR saatiyle 06:00
  workflow_dispatch: # Manuel çalıştırma butonu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests
          npm install -g firebase-tools

      - name: Run Master Scraper
        run: python scripts/master_scraper.py

      - name: Deploy to Firebase Hosting
        run: |
          npx firebase-tools deploy --only hosting --project epg-server-auto --token "${{ secrets.FIREBASE_TOKEN }}" -m "GitHub Action EPG Update"

      - name: Commit and push changes to GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add epg/*
          git commit -m "Master EPG updated" || exit 0
          git push
