name: Update Master EPG

on:
  schedule:
    - cron: '0 3 * * *' # Her gece TR saatiyle 06:00
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3 lxml playwright

      - name: Install Playwright Chromium
        run: |
          python -m playwright install --with-deps chromium

      - name: Run Master Scraper
        run: python scripts/master_scraper.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add epg/*
          git commit -m "Master EPG updated: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
